fix: continue using CythonRecipe for Pyjnius
Upstream changed the recipe for Pyjnius to use another base template in
https://github.com/kivy/python-for-android/commit/53deb85d5f51a6ae5e15785411aa1923b7eafff6
however this makes our build fail. Switching to the previous
CythonRecipe base template works fine.,
however this makes our build fail. Switching to the previous
CythonRecipe base template works fine.

fixes:
```
id/platform/build-x86_64/build/other_builds/pyjnius-sdl3/x86_64__ndk_target_23/pyjnius/p4a_android_build
[DEBUG]:        * Creating isolated environment: venv+pip...
[DEBUG]:        * Installing packages in isolated environment:
[DEBUG]:          - Cython
[DEBUG]:          - setuptools>=58.0.0
[DEBUG]:          - wheel
[DEBUG]:        * Getting build dependencies for wheel...
[DEBUG]:        Ignoring "sys._home = value" override
[DEBUG]:        warning: [options] bootstrap class path not set in conjunction with -source 8
[DEBUG]:        1 warning
[DEBUG]:        running egg_info
[DEBUG]:        creating pyjnius.egg-info
[DEBUG]:        writing pyjnius.egg-info/PKG-INFO
[DEBUG]:        writing dependency_links to pyjnius.egg-info/dependency_links.txt
[DEBUG]:        writing requirements to pyjnius.egg-info/requires.txt
[DEBUG]:        writing top-level names to pyjnius.egg-info/top_level.txt
[DEBUG]:        writing manifest file 'pyjnius.egg-info/SOURCES.txt'
[DEBUG]:        reading manifest file 'pyjnius.egg-info/SOURCES.txt'
[DEBUG]:        reading manifest template 'MANIFEST.in'
[DEBUG]:        adding license file 'LICENSE'
[DEBUG]:        writing manifest file 'pyjnius.egg-info/SOURCES.txt'
[DEBUG]:        * Installing packages in isolated environment:
[DEBUG]:          - wheel
[DEBUG]:        * Building wheel...
[DEBUG]:        Ignoring "sys._home = value" override
[DEBUG]:        warning: [options] bootstrap class path not set in conjunction with -source 8
[DEBUG]:        1 warning
[DEBUG]:        running bdist_wheel
[DEBUG]:        running build
[DEBUG]:        running build_py
[DEBUG]:        creating build
[DEBUG]:        creating build/lib.linux-x86_64-cpython-310
[DEBUG]:        copying jnius_config.py -> build/lib.linux-x86_64-cpython-310
[DEBUG]:        copying setup_sdist.py -> build/lib.linux-x86_64-cpython-310
[DEBUG]:        creating build/lib.linux-x86_64-cpython-310/jnius
[DEBUG]:        copying jnius/__init__.py -> build/lib.linux-x86_64-cpython-310/jnius
[DEBUG]:        copying jnius/env.py -> build/lib.linux-x86_64-cpython-310/jnius
[DEBUG]:        copying jnius/reflect.py -> build/lib.linux-x86_64-cpython-310/jnius
[DEBUG]:        copying jnius/signatures.py -> build/lib.linux-x86_64-cpython-310/jnius
[DEBUG]:        copying jnius/env.py -> build/lib.linux-x86_64-cpython-310/jnius
[DEBUG]:        creating build/lib.linux-x86_64-cpython-310/jnius/src
[DEBUG]:        creating build/lib.linux-x86_64-cpython-310/jnius/src/org
[DEBUG]:        creating build/lib.linux-x86_64-cpython-310/jnius/src/org/jnius
[DEBUG]:        copying jnius/src/org/jnius/NativeInvocationHandler.java -> build/lib.linux-x86_64-cpython-310/jnius/src/org/jnius
[DEBUG]:        copying jnius/src/org/jnius/NativeInvocationHandler.class -> build/lib.linux-x86_64-cpython-310/jnius/src/org/jnius
[DEBUG]:        running build_ext
[DEBUG]:        building 'jnius' extension
[DEBUG]:        creating build/temp.linux-x86_64-cpython-310
[DEBUG]:        creating build/temp.linux-x86_64-cpython-310/jnius
[DEBUG]:        /usr/bin/ccache /opt/android/android-ndk-r23d-canary/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -target x86_64-linux-android23 -fomit-frame-pointer -march=x86-64 -msse4.2 -mpopcnt -m64 -fPIC -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -target x86_64-linux-android23 -fomit-frame-pointer -march=x86-64 -msse4.2 -mpopcnt -m64 -fPIC -I/home/user/wspace/electrum/.buildozer/android/platform/build-x86_64/build/other_builds/python3/x86_64__ndk_target_23/python3/Include -DANDROID -I/opt/android/android-ndk-r23d-canary/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include -I/home/user/wspace/electrum/.buildozer/android/platform/build-x86_64/build/python-installs/Electrum/x86_64/include/python3.1 -fPIC -I/tmp/build-env-xph1qypj/include -I/usr/local/include/python3.10 -c jnius/jnius.c -o build/temp.linux-x86_64-cpython-310/jnius/jnius.o
[DEBUG]:        clang-12: error: no such file or directory: 'jnius/jnius.c'
[DEBUG]:        clang-12: error: no input files
[DEBUG]:        error: command '/usr/bin/ccache' failed with exit code 1
[DEBUG]:
[DEBUG]:        ERROR Backend subprocess exited when trying to invoke build_wheel
Exception in thread background thread for pid 186549:
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/venv/lib/python3.11/site-packages/sh.py", line 1642, in wrap
    fn(*rgs, **kwargs)
  File "/opt/venv/lib/python3.11/site-packages/sh.py", line 2647, in background_thread
    handle_exit_code(exit_code)
  File "/opt/venv/lib/python3.11/site-packages/sh.py", line 2338, in fn
    return self.command.handle_command_exit_code(exit_code)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/sh.py", line 823, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1:

  RAN: /home/user/wspace/electrum/.buildozer/android/platform/build-x86_64/build/other_builds/python3/x86_64__ndk_target_23/python3/android-build/python3 -m build --wheel --config-setting builddir=/home/user/wspace/electrum/.buildozer/android/platform/build-x86_64/build/other_builds/pyjnius-sdl3/x86_64__ndk_target_23/pyjnius/p4a_android_build

  STDOUT:
* Creating isolated environment: venv+pip...
* Installing packages in isolated environment:
  - Cython
  - setuptools>=58.0.0
  - wheel
* Getting build dependencies for wheel...
Ignoring "sys._home = value" override
warning: [options] bootstrap class path not set in conjunction with -source 8
1 warning
running egg_info
creating pyjnius.egg-info
writing pyjnius.egg-info/PKG-INFO
writing dependency_links to pyjnius.egg-info/dependency_links.txt
writing requirements to pyjnius.egg-info/requires.txt
writing top-level names to pyjnius.egg-info/top_level.txt
writing manifest file 'pyjnius.egg-info/SOURCES.txt'
reading manifest file 'pyjnius.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
adding license file 'LICENSE'
writing manifest file 'pyjnius.egg-info/SOURCES.txt'
* Installing packages in isolated environment:
  - wheel
* Building wheel...
Ignoring "sys._home = value" override
warning: [options] bootstrap class path not set in conjunction with -source 8
1 warning
running bdist_wheel
running build
running build_py
creating build
creating build/lib.linux-x86_64-cpython-310
copying jnius_config.py -> build/lib.linux-x86_64-cpython-310
copying setup_sdist.py -> build/lib.linux-x86_64-cpython-310
creating build/lib.linux-x86_64-cpython-310/jnius
copying jnius/__init__.py -> build/lib.linux-x86_64-cpython-310/jnius
copying jnius/env.py -> build/lib.linux-x86_64-cpython-310/jnius
copying jnius/reflect.py -> build/lib.linux-x86_64-cpython-310/jnius
copying jnius/signatures.py -> build/lib.linux-x86_64-cpython-310/jnius
copying jnius/env.py -> build/lib.linux-x86_64-cpython-310/jnius
creating build/lib.linux-x86_64-cpython-310/jnius/src
creating build/lib.linux-x86_64-cpython-310/jnius/src/org
creating build/lib.linux-x86_64-cpython-310/jnius/src/org/jnius
copying jnius/src/org/jnius/NativeInvocationHandler.java -> build/lib.linux-x86_64-cpython-310/jnius/src/org/jnius
copying jnius/src/org/jnius/NativeInvocationHandler.class -> build/lib.linux-x86_64-cpython-310/jnius/src/org/jnius
running build_ext
building 'jnius' extension
creating build/temp.linux-x86_64-cpython-310
creating build/temp.linux-x86_64-cpython-310/jnius
/usr/bin/ccache /opt/android/android-ndk-r23d-canary/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -target x86_64-linux-android23 -fomit-frame-pointer -march=x86-64 -msse4.2 -mpopcnt -m64 -fPIC -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -target x86_64-linux-android23 -fomit-frame-pointer -march=x86-64 -msse4.2 -mpopcnt -m64 -fPIC -I/home/user/wspace/electrum/.buildozer/android/platform/build-x86_64/build/other_builds/python3/x86_64__ndk_target_23/python3/Include -DANDROID -I/opt/android/android-ndk-r23d-canary/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include -I/home/user/wspace/electrum/.buildozer/android/platform/build-x86_64/build/python-installs/Electrum/x86_64/include/python3.1 -fPIC -I/tmp/build-env-xph1qypj/include -I/usr/local/include/python3.10 -c jnius/jnius.c -o build/temp.linux-x86_64-cpython-310/jnius/jnius.o
clang-12: error: no such file or directory: 'jnius/jnius.c'
clang-12: error: no input files
error: command '/usr/bin/ccache' failed with exit code 1

ERROR Backend subprocess exited when trying to invoke build_wheel

  STDERR:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/opt/spesmilo-python-for-android-fork-fork/pythonforandroid/toolchain.py", line 1246, in <module>
    main()
  File "/opt/spesmilo-python-for-android-fork-fork/pythonforandroid/entrypoints.py", line 18, in main
    ToolchainCL()
  File "/opt/spesmilo-python-for-android-fork-fork/pythonforandroid/toolchain.py", line 677, in __init__
    getattr(self, command)(args)
  File "/opt/spesmilo-python-for-android-fork-fork/pythonforandroid/toolchain.py", line 104, in wrapper_func
    build_dist_from_args(ctx, dist, args)
  File "/opt/spesmilo-python-for-android-fork-fork/pythonforandroid/toolchain.py", line 163, in build_dist_from_args
    build_recipes(build_order, python_modules, ctx,
  File "/opt/spesmilo-python-for-android-fork-fork/pythonforandroid/build.py", line 513, in build_recipes
    recipe.build_arch(arch)
  File "/opt/spesmilo-python-for-android-fork-fork/pythonforandroid/recipe.py", line 1289, in build_arch
    shprint(
  File "/opt/spesmilo-python-for-android-fork-fork/pythonforandroid/logger.py", line 167, in shprint
    for line in output:
  File "/opt/venv/lib/python3.11/site-packages/sh.py", line 879, in __next__
    self.wait()
  File "/opt/venv/lib/python3.11/site-packages/sh.py", line 796, in wait
    self.handle_command_exit_code(exit_code)
  File "/opt/venv/lib/python3.11/site-packages/sh.py", line 823, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1:

  RAN: /home/user/wspace/electrum/.buildozer/android/platform/build-x86_64/build/other_builds/python3/x86_64__ndk_target_23/python3/android-build/python3 -m build --wheel --config-setting builddir=/home/user/wspace/electrum/.buildozer/android/platform/build-x86_64/build/other_builds/pyjnius-sdl3/x86_64__ndk_target_23/pyjnius/p4a_android_build

  STDOUT:
* Creating isolated environment: venv+pip...
* Installing packages in isolated environment:
  - Cython
  - setuptools>=58.0.0
  - wheel
* Getting build dependencies for wheel...
Ignoring "sys._home = value" override
warning: [options] bootstrap class path not set in conjunction with -source 8
1 warning
running egg_info
creating pyjnius.egg-info
writing pyjnius.egg-info/PKG-INFO
writing dependency_links to pyjnius.egg-info/dependency_links.txt
writing requirements to pyjnius.egg-info/requires.txt
writing top-level names to pyjnius.egg-info/top_level.txt
writing manifest file 'pyjnius.egg-info/SOURCES.txt'
reading manifest file 'pyjnius.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
adding license file 'LICENSE'
writing manifest file 'pyjnius.egg-info/SOURCES.txt'
* Installing packages in isolated environment:
  - wheel
* Building wheel...
Ignoring "sys._home = value" override
warning: [options] bootstrap class path not set in conjunction with -source 8
1 warning
running bdist_wheel
running build
running build_py
creating build
creating build/lib.linux-x86_64-cpython-310
copying jnius_config.py -> build/lib.linux-x86_64-cpython-310
copying setup_sdist.py -> build/lib.linux-x86_64-cpython-310
creating build/lib.linux-x86_64-cpython-310/jnius
copying jnius/__init__.py -> build/lib.linux-x86_64-cpython-310/jnius
copying jnius/env.py -> build/lib.linux-x86_64-cpython-310/jnius
copying jnius/reflect.py -> build/lib.linux-x86_64-cpython-310/jnius
copying jnius/signatures.py -> build/lib.linux-x86_64-cpython-310/jnius
copying jnius/env.py -> build/lib.linux-x86_64-cpython-310/jnius
creating build/lib.linux-x86_64-cpython-310/jnius/src
creating build/lib.linux-x86_64-cpython-310/jnius/src/org
creating build/lib.linux-x86_64-cpython-310/jnius/src/org/jnius
copying jnius/src/org/jnius/NativeInvocationHandler.java -> build/lib.linux-x86_64-cpython-310/jnius/src/org/jnius
copying jnius/src/org/jnius/NativeInvocationHandler.class -> build/lib.linux-x86_64-cpython-310/jnius/src/org/jnius
running build_ext
building 'jnius' extension
creating build/temp.linux-x86_64-cpython-310
creating build/temp.linux-x86_64-cpython-310/jnius
/usr/bin/ccache /opt/android/android-ndk-r23d-canary/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -target x86_64-linux-android23 -fomit-frame-pointer -march=x86-64 -msse4.2 -mpopcnt -m64 -fPIC -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -target x86_64-linux-android23 -fomit-frame-pointer -march=x86-64 -msse4.2 -mpopcnt -m64 -fPIC -I/home/user/wspace/electrum/.buildozer/android/platform/build-x86_64/build/other_builds/python3/x86_64__ndk_target_23/python3/Include -DANDROID -I/opt/android/android-ndk-r23d-canary/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include -I/home/user/wspace/electrum/.buildozer/android/platform/build-x86_64/build/python-installs/Electrum/x86_64/include/python3.1 -fPIC -I/tmp/build-env-xph1qypj/include -I/usr/local/include/python3.10 -c jnius/jnius.c -o build/temp.linux-x86_64-cpython-310/jnius/jnius.o
clang-12: error: no such file or directory: 'jnius/jnius.c'
clang-12: error: no input files
error: command '/usr/bin/ccache' failed with exit code 1

ERROR Backend subprocess exited when trying to invoke build_wheel

```